/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublishersImport } from './routes/publishers'
import { Route as AuthorsImport } from './routes/authors'
import { Route as IndexImport } from './routes/index'
import { Route as BooksBookIdImport } from './routes/books/$bookId'

// Create/Update Routes

const PublishersRoute = PublishersImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => rootRoute,
} as any)

const AuthorsRoute = AuthorsImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BooksBookIdRoute = BooksBookIdImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsImport
      parentRoute: typeof rootRoute
    }
    '/publishers': {
      id: '/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof PublishersImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/publishers': typeof PublishersRoute
  '/books/$bookId': typeof BooksBookIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/publishers': typeof PublishersRoute
  '/books/$bookId': typeof BooksBookIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/publishers': typeof PublishersRoute
  '/books/$bookId': typeof BooksBookIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authors' | '/publishers' | '/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authors' | '/publishers' | '/books/$bookId'
  id: '__root__' | '/' | '/authors' | '/publishers' | '/books/$bookId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRoute
  PublishersRoute: typeof PublishersRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRoute,
  PublishersRoute: PublishersRoute,
  BooksBookIdRoute: BooksBookIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authors",
        "/publishers",
        "/books/$bookId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authors": {
      "filePath": "authors.tsx"
    },
    "/publishers": {
      "filePath": "publishers.tsx"
    },
    "/books/$bookId": {
      "filePath": "books/$bookId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
